name: Update Calendar

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build calendar
        run: python build_calendar.py

      - name: Commit ICS file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add calendar.ics

          if ! git diff --staged --quiet; then
            git commit -m "Update calendar"
            git push
          fi
